<?php
/**
 * Handles the "Forgot Password" process with IP-based rate limiting.
 *
 * This script displays a form for users to enter their email address.
 * On submission, it checks for rate limits, validates input, generates a
 * password reset token (if the email exists), stores it, and (for demonstration)
 * displays a reset link. In a production environment, this link would be emailed.
 */
require_once 'login_system/src/bootstrap.php'; // $authController, $user, $security, $rateLimiter

// A more robust IP getter could be moved to a utility function later
$clientIp = $_SERVER['REMOTE_ADDR'] ?? 'unknown'; // Fallback for CLI or misconfigured server

$authController->requireGuest(); // User should not be logged in

// $errors = []; // Not strictly used for logic if redirecting on each error. Flash messages are used.
$form_email_value = ''; // To repopulate form field on non-redirecting errors (not current flow)

// The POST request handling logic is now in handle_forgot_password.php
// It will use $clientIp, $security, $rateLimiter, $auditLogger, $authController, $user.
// It will also use and update $form_email_value (though redirects make this less visible).
require_once 'login_system/includes/handle_forgot_password.php';

// For GET requests, ensure CSRF token is generated.
// Flash messages are retrieved after the include, as the POST handler (which redirects) sets them.
if ($_SERVER['REQUEST_METHOD'] === 'GET') {
    $security->generateCsrfToken();
}

// Retrieve flash messages for display. These are set by handle_forgot_password.php before redirecting.
$successMessageHTML = $authController->getAndSetFlashMessage('success');
$infoMessageHTML = $authController->getAndSetFlashMessage('info');
// Error messages are typically displayed using display_flash_messages() which also uses sessions.

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forgot Password - <?php echo $security->escapeHTML(defined('SITE_NAME') ? SITE_NAME : 'Login System'); ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="login_system/css/style.css">
</head>
<body>
    <div class="container">
        <div class="auth-container">
            <h2 class="text-center mb-4">Forgot Password</h2>

            <?php display_flash_messages('errors', 'danger'); // Display any error flash messages ?>
            
            <?php if ($successMessageHTML): ?>
                <div class="alert alert-success">
                    <p class="mb-0"><?php echo $security->escapeHTML($successMessageHTML); // Success message is plain text ?></p>
                </div>
            <?php endif; ?>

            <?php if ($infoMessageHTML): ?>
                <div class="alert alert-info">
                    <?php /* Info message contains HTML (the link), generated by buildUrl which escapes for href. Displaying the link text itself is also escaped. */ ?>
                    <p class="mb-0"><?php echo $infoMessageHTML; ?></p>
                </div>
            <?php endif; ?>

            <?php if (!$successMessageHTML && !$infoMessageHTML): // Only show form if no success/info message is being displayed ?>
            <form id="forgotPasswordForm" method="POST" action="<?php echo $authController->buildUrl(PAGE_FORGOT_PASSWORD); ?>" novalidate>
                <?php echo $security->getCsrfInput(); ?>
                <div class="mb-3">
                    <label for="email" class="form-label">Enter your email address</label>
                    <input type="email" class="form-control" id="email" name="email" required value="<?php echo $form_email_value; // Repopulate on server-side validation error without redirect (not current flow) ?>">
                    <div class="invalid-feedback">Please enter a valid email.</div>
                </div>
                <button type="submit" class="btn btn-primary w-100">Send Reset Link</button>
            </form>
            <?php endif; ?>
            <p class="text-center mt-3">
                Remembered your password? <a href="<?php echo $authController->buildUrl(PAGE_SIGNIN); ?>">Sign In</a>
            </p>
        </div>
    </div>

    <script>
        // Standard Bootstrap validation script
        (function() {
            'use strict';
            window.addEventListener('load', function() {
                var form = document.getElementById('forgotPasswordForm');
                if (!form) return;
                form.addEventListener('submit', function(event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            }, false);
        })();
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
